### ISSUE TITLE
buildpackages+openstack: support Leap 42.2

### ISSUE THREAD

**Issue by smithfarm** [SUSE/teuthology#29]
There is no particular hurry since the test suites run on Leap 42.1, but eventually we should move to 42.2.

The roadblock is that there is no OpenStack image at http://download.opensuse.org/repositories/Cloud:/Images:/Leap_42.2/images/

There is a bzip2'd tarball containing Leap 42.2 rootfs, but not a qcow2 like there is for Leap 42.1 at http://download.opensuse.org/repositories/Cloud:/Images:/Leap_42.1/images/

**Comment by smithfarm** [comment]
Asked bmwiedemann at https://hackweek.suse.com/projects/2030

**Comment by bmwiedemann** [comment]
Trying to build that image in https://build.opensuse.org/package/show/Cloud:Images:Leap_42.2/openSUSE-Leap-42.2-OpenStack-Guest but since I'm not a kiwi expert, it might take a while.

**Comment by smithfarm** [comment]
@bmwiedemann If you need help, let me know.

**Comment by bmwiedemann** [comment]
http://download.opensuse.org/repositories/Cloud:/Images:/Leap_42.2/images/openSUSE-Leap-42.2-OpenStack.x86_64.qcow2 built. I imported it into https://stable.cloud.suse.de/ and it is working.

**Comment by smithfarm** [comment]
\o/ \o/ \o/ thanks @bmwiedemann
