### ISSUE TITLE
YAML files referenced on teuthology-openstack command line are not transferred to teuthology machine

### ISSUE THREAD

**Issue by smithfarm** [SUSE/teuthology#56]
`teuthology-openstack` is designed to be run on a "local machine" - under the hood, `t-o` runs itself on the _remote_ teuthology machine after determining that it exists (and creating/provisioning it if necessary). The _remote_ `t-o` command then, eventually, issues a `teuthology-suite` command.

If a YAML file is specified on the `t-o` command line, this gets passed all the way through to `teuthology-suite`, which looks for it on the teuthology machine.

If the file is specified as an absolute path, `t-o` should try to upload the file to the teuthology machine.

**Comment by smithfarm** [comment]
@jan--f Would this address your question in #46 ?

**Comment by jan--f** [comment]
@smithfarm yes I think that would work quite well. Initially I had thought about passing a yaml string, but that offers only limited practicality in terms of the amount of options passed.

**Comment by smithfarm** [comment]
I guess `t-o` should check if that path/file already exists on the teuthology VM, first, and refuse to upload it if it does. But otherwise I agree this seems pretty fruity!

**Comment by smithfarm** [comment]
@jan--f There's another caveat. If I supply `~/foo.yaml` on the `t-o` commandline, in my case the shell will expand this to `/home/smithfarm/foo.yaml`. On the teuthology machine, there is no `/home/smithfarm` to copy the file into. But I guess that's not a problem. Just do `mkdir -p` on the dirname before copying.

**Comment by jan--f** [comment]
Maybe not quite ``` mkdir -p /home/smithfarm/ ``` but something like ``` mkdir -p /home/ubuntu/sensible_dir/home/smithfarm/ ``` ?

**Comment by smithfarm** [comment]
oh, good idea! implementing it.

**Comment by smithfarm** [comment]
Any idea what's going on with this?

```
2017-03-15 15:42:03,236.236 DEBUG:ceph_workbench.util:2017-03-15 15:42:03,235.235 DEBUG:teuthology.misc::sh: sudo -s "mkdir -p /home/ubuntu/yaml/home/smithfarm"
2017-03-15 15:42:03,276.276 DEBUG:ceph_workbench.util:2017-03-15 15:42:03,276.276 DEBUG:teuthology.misc:/bin/bash: mkdir -p /home/ubuntu/yaml/home/smithfarm: No such file or directory
```
