### ISSUE TITLE
teuthology-worker security group is not created

### ISSUE THREAD

**Issue by dachary** [SUSE/teuthology#62]
If the teuthology security group already exists but the teuthology-worker security group is missing, it will not be created

```
        """
        try:
            self.run("security group show teuthology")
            return
        except subprocess.CalledProcessError:
            pass
        # FIXME: the following assumes "--name teuthology"
        misc.sh("""
openstack security group create teuthology
openstack security group create teuthology-worker

```

**Comment by jan--f** [comment]
Currently I assume to start from scratch with that. That means if a teuthology security groups is found, the setup is skipped. So as a work around you can wipe your teuthology-openstack instance from the horizoon interface, including the security group.
Its probably not enough to add a check for teuthology-worker here https://github.com/SUSE/teuthology/blob/master/teuthology/openstack/__init__.py#L886
Wondering how ```openstack security group create``` ```and ```openstack security groupe rule create``` behave when groups or rules exist.

**Comment by dachary** [comment]
You could 

    self.run("security group show teuthology && security group show teuthology-worker")

and add a 

     openstack security group delete teuthology || true
     openstack security group delete teuthology-worker || true

before

     openstack security group create teuthology

it should take care of all cases or am I missing something ?

**Comment by jan--f** [comment]
Sounds pretty solid. Will make a PR
