### ISSUE TITLE
DeepSea suite development workflow

### ISSUE THREAD

**Issue by smithfarm** [SUSE/teuthology#71]
Each individual test would take the form of a bash script. This collection of integration testing scripts would live in a subdirectory inside the DeepSea code repo on github.

Each test script would start with a comment block - something like the following (note: this is just a draft proposal):

```
#!/bin/bash -ex
#
# DeepSea integration test workunit "basic-health-ok"
#
# This integration test script makes the following assumptions:
# 1. there are four machines that are running the same OS (e.g. Leap 42.3) and
#    can see eachother over the network:
#    - Salt Master/admin node
#    - mon.a
#    - mon.b
#    - mon.c
# 2. Salt Master/admin node need have no external drives
# 3. nodes mon.{a,b,c} need at least one external drive (>= 20GB) for OSD
# 4. the integration test script is running on Salt Master/admin node
# 5. the Salt Master/admin node has:
#    - salt-master package installed
#    - salt-master.service enabled and started
# 6. the mon.{a,b,c} nodes have:
#    - salt-minion package installed
#    - salt-minion.service enabled and started
# 7. the Salt Master/admin node has accepted all the minion keys and test.ping
#    has succeeded against all three nodes mon.{a,b,c}
# 8. the ceph RPMs under test have already been installed on nodes mon.{a,b,c}
# 9. the DeepSea code under test has already been installed on Salt
#    Master/admin node
#
# This script deploys a Ceph cluster on nodes mon.{a,b,c} and checks for
# HEALTH_OK.
#
# On success (HEALTH_OK is reached), the script returns 0.
#
# On failure, for whatever reason, the script returns non-zero.
#
# The script produces verbose output on stdout for capture and later forensic
# analysis.
```

When run outside of teuthology, it would be up to the user to provide the environment.

When run inside of teuthology, there would be yaml like this:

```
roles:
- - master.1
  - mon.a
  - mon.b
  - mon.c
openstack:
  - volumes:
      count: 1
      size: 20 # GB
ceph_cm: salt
tasks:
- install: null
- deepsea: null
- workunit:
    clients:
      master.1:
      - deepsea/basic-health-ok.sh
```

The `install` task would take care of installing the ceph RPMs on the target VMs.

The `deepsea` task would take care of salt-master and salt-minion deployment/setup, key acceptance, test.ping (using the Salt class from teuthology) and install DeepSea code (git clone. . .) on master.1

The `deepsea/basic-health-ok.sh` workunit script would live in the ceph repository under `qa/workunits/` and it would very simply grab the script from github and run it.

**Comment by smithfarm** [comment]
@jan--f @rjfd How does this look?

**Comment by rjfd** [comment]
@smithfarm this looks be the way to go :+1:

**Comment by jan--f** [comment]
@smithfarm yes sounds good to me too. I guess we could add a code pice to each script that checks that its prerequisites are met?
Also the yaml file for a certain test could be useful outside of teuthology too. Though I don't have an idea for how to avoid having the yaml in deepsea and teuthology...just seems like the test specification could be used for other tools too.

**Comment by smithfarm** [comment]
Regarding the yaml, I guess the only part of it the non-teuthology use case needs is the `roles` stanza. There needs to be a way to select nodes (via salt) using the same names as are in the `roles` stanza (e.g. "mon.a"). 

In the past, I have done this by defining a grain. For example:

```
salt -G 'role:mon.a' test.ping
```

That would be easy to implement on the teuthology side. I don't know how it would be implemented on the non-teuthology side, but I wouldn't get too hung up on avoiding duplication of the yaml.

**Comment by smithfarm** [comment]
> I guess we could add a code pice to each script that checks that its prerequisites are met?

Yes, the workunit script could (optionally?) start with sanity checks. For example, we could implement a check that would parse the `roles` stanza and ping the nodes via salt, to affirm that they exist and are reachable under those names.

**Comment by rjfd** [comment]
I've added a first example of basic-health-ok.sh here: https://github.com/rjfd/DeepSea/blob/wip-teuthology-suite/qa/workunits/suites/basic-healt-ok.sh

The script does not rely on the roles stanza of teuthology. Currently I'm selecting all minions as monitors, but I'll change that to allow the programmer to specify how many minions should be configured for each kind of role.

@smithfarm @jan--f can you run the script using teuthology and see if it works?

**Comment by smithfarm** [comment]
> @smithfarm @jan--f can you run the script using teuthology and see if it works?

Done, works great. Development ongoing in https://github.com/SUSE/ceph/tree/wip-deepsea-suite
