### ISSUE TITLE
Support new OVH flavors

### ISSUE THREAD

**Issue by smithfarm** [SUSE/teuthology#77]
OVH has revamped their flavors - the new flavors are active in the "new" regions (currently GRA3 and SBG3). Here is the list: https://www.ovh.com/us/public-cloud/instances/prices/

To obtain the flavor name, convert the string in the "Model" column to lower case (e.g. "S1-2" -> "s1-2") are identical to the flavor names.

The "cheap" flavors are: "s1-2", "s1-4", and "s1-8" (listed under "SANDBOX instances" at the bottom of the linked page).

To support these newer regions we will need to tweak the regular expressions in `teuthology/openstack/__init__.py`

**Comment by kshtsk** [comment]
@smithfarm I think we can resolve it now, right?

**Comment by smithfarm** [comment]
@kshtsk Can you link the PR that fixed it?

**Comment by kshtsk** [comment]
@smithfarm this is #109 and #124
