### ISSUE TITLE
salt-master on teuthology VM dies and cannot be restarted

### ISSUE THREAD

**Issue by smithfarm** [SUSE/teuthology#87]
DeepSea suite test runs started to fail because ceph-cm-salt could not complete because the salt-master.service could not be restarted. Indeed, on the teuthology VM the salt-master.service is failed and cannot be restarted. This is all journalctl has to say about it:

```
Jun 20 21:03:05 teuthology systemd[1]: Starting The Salt Master Server...
-- Subject: Unit salt-master.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit salt-master.service has begun starting up.
Jun 20 21:03:06 teuthology salt-master[16722]: [WARNING ] Key 'file_ignore_glob' with value None has an invalid type of No
Jun 20 21:03:06 teuthology salt-master[16722]: [WARNING ] Unable to bind socket, error: [Errno 98] Address already in use
Jun 20 21:03:06 teuthology salt-master[16722]: The ports are not available to bind
Jun 20 21:03:06 teuthology systemd[1]: salt-master.service: Main process exited, code=exited, status=4/NOPERMISSION
Jun 20 21:03:06 teuthology systemd[1]: Failed to start The Salt Master Server.
-- Subject: Unit salt-master.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit salt-master.service has failed.
-- 
-- The result is failed.
```

And `/var/log/salt/master` is not much more helpful:

```
2017-06-20 12:41:47,232 [salt.utils.verify][WARNING ][13547] Unable to bind socket, error: [Errno 98] Address already in use
2017-06-20 12:52:57,339 [salt.utils.verify][WARNING ][14509] Unable to bind socket, error: [Errno 98] Address already in use
2017-06-20 21:03:06,221 [salt.utils.verify][WARNING ][16722] Unable to bind socket, error: [Errno 98] Address already in use
```

@jan--f Could you take a look before I tear down this teuthology VM?

**Comment by rjfd** [comment]
@smithfarm maybe another salt-master process is already running?

**Comment by smithfarm** [comment]
Indeed, there are two running:

```
(virtualenv) root@teuthology:/var/log/salt# ps ax | grep salt-master
11878 ?        Sl     0:00 /usr/bin/python /usr/bin/salt-master
11879 ?        Sl     0:00 /usr/bin/python /usr/bin/salt-master
16801 pts/0    R+     0:00 grep --color=auto salt-master
```

**Comment by smithfarm** [comment]
The question is, why does `systemctl restart salt-master.service` fail and why does `systemctl stop salt-master.service` not cause these processes to exit?

**Comment by smithfarm** [comment]
Hmm, this coincided with a `deepsea/basic` run which spawned five jobs, each of which ran ceph-cm-salt at about the same time. And ceph-cm-salt is doing `systemctl restart salt-master.service` on the teuthology VM.

**Comment by jan--f** [comment]
> 
> ```(virtualenv) root@teuthology:/var/log/salt# ps ax | grep salt-master
> 11878 ?        Sl     0:00 /usr/bin/python /usr/bin/salt-master
> 11879 ?        Sl     0:00 /usr/bin/python /usr/bin/salt-master
> 16801 pts/0    R+     0:00 grep --color=auto salt-master```

You see this when the salt-master service is in the failed state?
Are me hitting this? https://github.com/saltstack/salt/issues/20903#issuecomment-185233823
Though it could be that we hit this:

**Comment by smithfarm** [comment]
Yeah, as "cachedout" notes in that bug: "It was not shutdown cleanly. You need to kill all salt-master processes before attempting to restart."

To prevent this from happening, I'll implement a locking mechanism to ensure that test jobs take turns restarting the salt-master.service.

**Comment by smithfarm** [comment]
I'm thinking to use this: http://fasteners.readthedocs.io/en/latest/examples.html#interprocess-locks
